Resources:
  orderPizzaLambdaHandlerServiceRoleB702EDD5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/orderPizzaLambdaHandler/ServiceRole/Resource
  orderPizzaLambdaHandler58F6696E:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          accountId:
            Ref: AWS:AccountId
          region:
            Ref: AWS:Region
      Code:
        S3Bucket:
          Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3BucketE8855DA7
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3VersionKey4C58EF06
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3VersionKey4C58EF06
      Role:
        Fn::GetAtt:
          - orderPizzaLambdaHandlerServiceRoleB702EDD5
          - Arn
      Handler: orderPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - orderPizzaLambdaHandlerServiceRoleB702EDD5
    Metadata:
      aws:cdk:path: TheStateMachineStack/orderPizzaLambdaHandler/Resource
      aws:asset:path: asset.2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642
      aws:asset:property: Code
  cookPizzaLambdaHandlerServiceRole6C0DB721:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/cookPizzaLambdaHandler/ServiceRole/Resource
  cookPizzaLambdaHandler1AFD5F5C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3BucketE8855DA7
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3VersionKey4C58EF06
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3VersionKey4C58EF06
      Role:
        Fn::GetAtt:
          - cookPizzaLambdaHandlerServiceRole6C0DB721
          - Arn
      Handler: cookPizza.handler
      Runtime: nodejs12.x
    DependsOn:
      - cookPizzaLambdaHandlerServiceRole6C0DB721
    Metadata:
      aws:cdk:path: TheStateMachineStack/cookPizzaLambdaHandler/Resource
      aws:asset:path: asset.2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - orderPizzaLambdaHandler58F6696E
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - cookPizzaLambdaHandler1AFD5F5C
                - Arn
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Order Pizza Job","States":{"Order Pizza Job":{"Next":"Cook Pizza Job","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Catch":[{"ErrorEquals":["NotAvailableFlavourError"],"Next":"Unavailable Flavour Selected"}],"Type":"Task","InputPath":"$","ResultPath":"$.order","Resource":"'
            - Fn::GetAtt:
                - orderPizzaLambdaHandler58F6696E
                - Arn
            - '"},"Cook Pizza Job":{"Next":"Failed","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$","ResultPath":"$.order","Resource":"'
            - Fn::GetAtt:
                - cookPizzaLambdaHandler1AFD5F5C
                - Arn
            - '"},"Failed":{"Type":"Choice","Choices":[{"Variable":"$.order.failed","BooleanEquals":true,"Next":"Sorry, Problem Cooking Pizza"}],"Default":"Deliver your pizza"},"Deliver your pizza":{"Type":"Succeed","OutputPath":"$.order"},"Sorry, Problem Cooking Pizza":{"Type":"Fail","Error":"Failed To Make Pizza","Cause":"Cooking failure"},"Unavailable Flavour Selected":{"Type":"Fail"}},"TimeoutSeconds":300}'
      StateMachineType: EXPRESS
      TracingConfiguration:
        Enabled: true
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Resource
  HttpApiRole79B5C31A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: states:StartSyncExecution
                Effect: Allow
                Resource:
                  Ref: StateMachine2E01A3A5
            Version: "2012-10-17"
          PolicyName: AllowSFNExec
    Metadata:
      aws:cdk:path: TheStateMachineStack/HttpApiRole/Resource
  thestatemachineapi69C81CC4:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: the-state-machine-api
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/Resource
  thestatemachineapiDefaultStageE23A2C15:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/DefaultStage/Resource
  Integ:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      IntegrationType: AWS_PROXY
      ConnectionType: INTERNET
      CredentialsArn:
        Fn::GetAtt:
          - HttpApiRole79B5C31A
          - Arn
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0"
      RequestParameters:
        Input: $request.body
        StateMachineArn:
          Ref: StateMachine2E01A3A5
      TimeoutInMillis: 10000
    Metadata:
      aws:cdk:path: TheStateMachineStack/Integ
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: Integ
    Metadata:
      aws:cdk:path: TheStateMachineStack/DefaultRoute
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAA11Q0U7DMAz8Ft7TjAIvvLFNmjYJxFS+wKRe57VNqtjpNFX9d5KMSogn31ln+86lLstX/fjwBlcuTN2uJuM86ulLwLRqzYwSYUO2UVtnWXwworYnewQPPQr6RD6DDCG3K2QXvMGEo74mIWdnlZZPHfTfNehpF6xJ7aRZ8KwIej1VrsujuR5dR+aWj2U0K34uIDlinY1FrjfBtCgbYFQsOJx+93EhwC3r93zzYEfX/hPEiMEYxFrtgDq1PTuKtmNWwQ8wZ7LZyF8eYwzURH6F2/ikp73IsB4oyVJJNL1qmbuDgxVsPCx5KxcE53lW1tWoL7wa4/df4v8vTFT4YIV61NW9/gC3k04RnAEAAA==
    Metadata:
      aws:cdk:path: TheStateMachineStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3BucketE8855DA7:
    Type: String
    Description: S3 bucket for asset "2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642"
  AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642S3VersionKey4C58EF06:
    Type: String
    Description: S3 key for asset version "2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642"
  AssetParameters2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642ArtifactHash6687B69C:
    Type: String
    Description: Artifact hash for asset "2af6a884f448bf2ef4363051461155e489de4520b953fb243786a7f2a2ddf642"
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: thestatemachineapi69C81CC4
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
